services:
  maildrop:
    image: haileyydev/maildrop:latest
    container_name: maildrop
    restart: unless-stopped
    ports:
      - "80:5000"
      - "25:25"
    environment:
      - DOMAIN=yourdomain.com
